#!/usr/bin/env python3
"""make_brand_assets.py — derive the site's logo and favicon from the Actian
brand SVG, without editing the brand asset by hand.

Input   tools/brand/actian-logo-white.svg              (the supplied asset)
Outputs zensical-site/docs/assets/images/actian-logo-white.svg
        zensical-site/docs/assets/images/actian-logo-dark.svg
        zensical-site/docs/assets/images/favicon.svg
        zensical-site/overrides/partials/logo.html

The brand asset lives outside docs/ so that it is the source of truth rather
than a file in the generated tree, and build.py regenerates all four outputs on
every run — a deleted logo then repairs itself instead of shipping a broken
image.

Why the two derivations:

* The supplied logo is the white-on-dark variant, but the Zensical "modern"
  header is light in light mode and dark in dark mode. So a second file is
  derived for light headers, with the white parts in the darkest colour of the
  mark's own gradient, and the partial ships both and lets CSS pick. (They are
  <img> tags rather than inline SVG: the lockup is 19 KB, which would be
  duplicated into every one of the 1,500+ pages.)
* A favicon is 16-32 px, so it uses the mark only. Its white strokes would
  disappear on a light browser tab, so they take the darkest colour from the
  mark's own gradient (#000178) instead of an invented one.

Usage: python3 tools/flare2md/make_brand_assets.py
"""
from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
SITE = REPO / "zensical-site"
SOURCE = REPO / "tools" / "brand" / "actian-logo-white.svg"
LOGO_WHITE = SITE / "docs" / "assets" / "images" / "actian-logo-white.svg"
LOGO_PARTIAL = SITE / "overrides" / "partials" / "logo.html"
LOGO_DARK = SITE / "docs" / "assets" / "images" / "actian-logo-dark.svg"
FAVICON = SITE / "docs" / "assets" / "images" / "favicon.svg"

# Darkest stop of the mark's gradient; used where white would be invisible.
BRAND_DARK = "#000178"

PARTIAL = """{#-
  Generated by tools/flare2md/make_brand_assets.py from
  docs/assets/images/actian-logo-white.svg — regenerate rather than edit.

  Both variants ship; extra.css shows the one that suits the current palette
  (the white lockup on the dark header, the dark lockup on the light header).
-#}
<img src="{{ 'assets/images/actian-logo-dark.svg' | url }}"
     class="jsd-logo jsd-logo--on-light" alt="Actian">
<img src="{{ 'assets/images/actian-logo-white.svg' | url }}"
     class="jsd-logo jsd-logo--on-dark" alt="Actian">
"""


def main() -> int:
    if not SOURCE.is_file():
        raise SystemExit("brand asset missing: %s" % SOURCE)
    svg = SOURCE.read_text(encoding="utf-8")
    LOGO_WHITE.parent.mkdir(parents=True, exist_ok=True)
    LOGO_WHITE.write_text(svg, encoding="utf-8")
    paths = re.findall(r"<path\b[^>]*/>", svg)
    defs = re.search(r"<defs>.*?</defs>", svg, re.S)
    if len(paths) < 3 or defs is None:
        raise SystemExit("unexpected structure in %s" % SOURCE)

    # ---- light-header variant: white -> the mark's darkest brand colour -- #
    LOGO_DARK.write_text(
        svg.replace('fill="white"', 'fill="%s"' % BRAND_DARK), encoding="utf-8"
    )

    # ---- header partial -------------------------------------------------- #
    LOGO_PARTIAL.parent.mkdir(parents=True, exist_ok=True)
    LOGO_PARTIAL.write_text(PARTIAL, encoding="utf-8")

    # ---- favicon: the mark only ------------------------------------------ #
    mark = [p.replace('fill="white"', 'fill="%s"' % BRAND_DARK) for p in paths[:3]]
    favicon = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 66 56" '
        'width="66" height="56" fill="none" role="img" aria-label="Actian">\n'
        "  %s\n%s\n</svg>\n" % ("\n  ".join(mark), defs.group(0))
    )
    FAVICON.write_text(favicon, encoding="utf-8")

    print("logo    -> %s, %s (%d paths)"
          % (LOGO_WHITE.name, LOGO_DARK.name, len(paths)))
    print("partial -> %s" % LOGO_PARTIAL)
    print("favicon -> %s (mark only)" % FAVICON)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
